variables:
    Version: 3.1.$(Build.BuildId)

stages:
    - stage: Build
      jobs:
          - job: Build
            pool:
                vmImage: Ubuntu 16.04
            steps:
                - task: UseDotNet@2
                  displayName: 'Install .Net Core 3.0'
                  inputs:
                      packageType: sdk
                      version: 3.1.100
                      includePreviewVersions: true

                - task: DotNetCoreCLI@2
                  displayName: 'Restore packages'
                  inputs:
                      command: restore
                      projects: '**/*.csproj'
                      feedsToUse: 'select'
                      verbosityRestore: 'minimal'
                      vstsFeed: 'BioEngine'
                      
                - task: DotNetCoreCLI@2
                  displayName: 'Publish project'
                  inputs:
                      command: custom
                      custom: publish
                      publishWebProjects: false
                      zipAfterPublish: false
                      modifyOutputPath: false
                      arguments: '--no-restore -c Release --output ./publish'
                      projects: '**/*.csproj'
                      
                - task: PublishPipelineArtifact@0
                  displayName: 'Publish app as artifact'
                  inputs:
                      artifactName: 'publish'
                      targetPath: './publish'

    - stage: Deploy
      dependsOn: Build
      condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
      jobs:
          - job: Publish
            pool:
                vmImage: Ubuntu 16.04
            steps:
                - download: current
                  artifact: publish
                - task: Docker@2
                  displayName: 'Build and push image'
                  inputs:
                      containerRegistry: 'BioWareRU DockerHub'
                      repository: 'biowareru/patreon-service'
                      command: 'buildAndPush'
                      Dockerfile: 'src/Dockerfile'
                      buildContext: '$(Pipeline.Workspace)/publish'
                      tags: '$(Version)'
